### ISSUE TITLE
Top coders location

### ISSUE THREAD

**Issue by JCarlosR** [joelibaceta/top-coders-peru#2]
Hi.
One workmate shared your repo, and it is very interesting. Congratulations.

I wanted to see the position of some friends and I, but realized it's only taking in consideration `location Lima`: 
https://github.com/joelibaceta/top-coders-peru/blob/1d14471d5e877a6b66d0fc3f6669541895bf90bb/_plugins/top_users_tag.rb#L101

Unfortunately if we replace it to `Peru`, it doesn't include all of the regions either.

What's your opinion? I didn't try Ruby yet, but it could be a good opportunity jeje.

**Comment by joelibaceta** [comment]
@JCarlosR included in https://github.com/joelibaceta/top-coders-peru/commit/14385d9175b2d5c27178a72a07d64849b0d5d9a9

**Comment by JCarlosR** [comment]
I see the location field accepts any arbitrary value (I was able to update "Trujillo" to "asd" in my profile). That's a bit sad, I thought it had an autocompletion feature. 
This way some people may be typing their city names, and others city + country.
Thank you anyway for the update.
