### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by CristianPumaES6** [joelibaceta/top-coders-peru#8]
Yo como usuario quisiera poder buscar mi user y saber en que puesto estoy.

**Comment by joelibaceta** [comment]
@CristianPumaES6 podría hacerse una aproximación en función a los puntajes, por lo pronto debido a la restricción del API de GitHub no podemos ponderar realmente el total de usuarios de GitHub por eso tomamos el top 40, seria complicado por ejemplo buscar un usuario en la posicion 3000, pero se puede estimar considerando la distribución de puntajes del top.

**Comment by CristianPumaES6** [comment]
Gracias @joelibaceta por tu explicacion.
